### ISSUE TITLE
Error: Error renaming temporary file to C:/Users/USE/Desktop/FO/1/compressed/9CAHAM-5.JPG

### ISSUE THREAD

**Issue by loverdeveloper** [photostructure/exiftool-vendored.js#105]
- Windows 11

Something terrible happened:  Error: Error renaming temporary file to C:/Users/USE/Desktop/FO/1/compressed/9CAHAM-5.JPG
    at WriteTask.parser (C:\neville\node_modules\exiftool-vendored\src\ExifToolTask.ts:16:15)
    at WriteTask.resolve (C:\neville\node_modules\batch-cluster\src\Task.ts:156:38)

**Comment by mceachen** [comment]
Please follow the bug report template.
