### ISSUE TITLE
AWS Lambda - BatchProcess - "cannot reject already-fulfilled task"

### ISSUE THREAD

**Issue by SDBurt** [photostructure/exiftool-vendored.js#112]
**Describe the bug**
I have been working on implementing `exiftool-vendored` into a lambda function, but have been running into many issues. The main one that has stumped me is an error related to an internal error captured by the `internalError` event listener.

```
BatchProcess(24).onError(Error: stdin.error: write EPIPE) cannot reject already-fulfilled task.
```

I have `exiftool-vendored` and `exiftool-vendored.pl` in an AWS Lambda Layer with the shebang changed to use `/opt`, and `getExif` changes to point to the layer's `exiftool-vendored.pl` (`/opt/exiftool-vendored.pl/bin/exiftool`), as well as perl (`perl-5-36-runtime-al2-x86_64`). This combination make it so I can have `ignoreShebang` set to false.

I have tried a few different angles to try and get things to work. I can execute an exiftool process using `child_process` and `exec` and print the version without any issues. Both with and without the `ignoreShebang` don't seem to change this error

Below are the logs and the sample code I used when trying to get things to work.

The full logs read
```
START RequestId: c2ab9344-8a30-4ea9-8a66-b071ce63242f Version: $LATEST
2022-07-07T17:40:46.461Z	c2ab9344-8a30-4ea9-8a66-b071ce63242f	INFO	Begin
2022-07-07T17:40:46.462Z	c2ab9344-8a30-4ea9-8a66-b071ce63242f	INFO	Starting
2022-07-07T17:40:46.517Z	c2ab9344-8a30-4ea9-8a66-b071ce63242f	INFO	childStart:
2022-07-07T17:40:46.576Z	c2ab9344-8a30-4ea9-8a66-b071ce63242f	INFO	Child internalError:  Error: BatchProcess(24).onError(Error: stdin.error: write EPIPE) cannot reject already-fulfilled task.
    at BatchProcess._BatchProcess_onError (/opt/nodejs/node_modules/batch-cluster/dist/BatchProcess.js:449:54)
    at Socket.<anonymous> (/opt/nodejs/node_modules/batch-cluster/dist/BatchProcess.js:88:118)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
2022-07-07T17:40:46.598Z	c2ab9344-8a30-4ea9-8a66-b071ce63242f	INFO	childEnd:
END RequestId: c2ab9344-8a30-4ea9-8a66-b071ce63242f
REPORT RequestId: c2ab9344-8a30-4ea9-8a66-b071ce63242f	Duration: 140.09 ms	Billed Duration: 141 ms	Memory Size: 256 MB	Max Memory Used: 66 MB	Init Duration: 237.39 ms
```

Test function
```typescript
const ExifTool = require("/opt/exiftool-vendored").ExifTool;

exports.handler = async (event) => {
    console.log("Begin");

    const exiftool = new ExifTool({
      ignoreShebang: true,
    });

    let version = undefined;
    console.log("Starting");

    exiftool.on('internalError', data => {
        console.log("Child internalError: ", data);
    });


    exiftool.on("childStart", (data) => {
        console.log(`childStart:`);
    });

    exiftool.on("childEnd", (data) => {
        console.log(`childEnd:`);
    });
    
    exiftool.on("taskData", (data) => {
        console.log(`taskData:`);
        console.log(data);
    });

    exiftool.on("taskResolved", (data) => {
        console.log(`taskResolved:`);
        console.log(data);
    });
    exiftool.on('taskError', data => {
        console.log("Child taskError: ", data);
    });

    const ver = new Promise(async(resolve, reject) => {
        const ver = await exiftool.version();
        resolve(ver);
      });

    try {
      version = await ver;
      console.log(`Version: v${version}`);
    } catch (err) {
      console.error(err);
    }

    console.log("Completed Version Check");

    console.log("End");

    const response = {
        statusCode: 200,
        body: JSON.stringify('Hello from Lambda!'),
    };
    return response;
};
```

**To Reproduce**
- Create a lambda function and use the above code.
- Create a lambda layer which has:
   - The exiftool's (exiftool-vendored.pl/bin/exiftool) shebang set to `#!/opt/bin/perl -w`
   - set the `findExiftool()` function to point to `/opt/exiftool-vendored`, or use the path in the exiftool constructor options? (have not tested this)

**Expected behavior**
The example code should print `Version: v${version}`

**Environment (please complete the following information):**
 - AWS Lambda function
 - Node.JS version: Node.js 14.x

**Comment by mceachen** [comment]
Sorry, this library doesn't support AWS Lambda. 

If I had to use that platform, I'd use a library that directly read from file headers (rather than spawning an external process). Unfortunately, I couldn't find one that was robust, which is why I wrote this library in the first place. There may be new alternatives now, though.

Good luck!

**Comment by SDBurt** [comment]
Thanks for the quick reply and the feedback. There are a bunch that I have attempted to use, but this library is much more feature-rich, especially for extracting binary data.

Cheers.

**Comment by mceachen** [comment]
Thanks for the kind words: there are a bunch of older discussions here: https://github.com/photostructure/exiftool-vendored.js/issues?q=is%3Aissue+lambda

(but I think you're going to be fighting lambda's external-process-killing service, hence my guidance above)
