### ISSUE TITLE
extractThumbnail fails for images with special characters in the filename on Windows

### ISSUE THREAD

**Issue by jrast** [photostructure/exiftool-vendored.js#124]
It seems like extracting thumbnails from images with special characters in the name fails. I'm using the following code to extract the thumbnail from an image:

````
import { exiftool } from 'exiftool-vendored'
import * as path from 'path'

const file = './dummy_data/IMG_6176 - Cöpy.cr2'
const filePath = path.resolve(file)

async function extractThumbnail(file): Promise<void> {
  const outFile = file + '.thumbnail.jpg'
  console.log(`Extracting Thumbnail of ${file} -> ${outFile}`)
  return exiftool
    .extractThumbnail(file, file + '.thumbnail.jpg')
    .then(() => console.log('Thumbnail extracted'))
    .catch((error) => console.log('Thumbnail extraction failed:', error))
}

async function getExifTags(file): Promise<void> {
  return exiftool.read(file).then((tags) => {
    console.log(`Make: ${tags.Make}, Model: ${tags.Model}, Errors: ${tags.errors}`)
    console.log(`Description: ${tags.Description}`)
    console.log(`Keywords: ${tags.Keywords}`)
    console.log(`Rating: ${tags.Rating}`)
  })
}

async function main() {
  try {
    await getExifTags(filePath)
    await extractThumbnail(filePath)
  } finally {
    exiftool.end()
  }
}

main().then(() => console.log('Done!'))
````
And I'm getting the following Error:
````
Extracting Thumbnail of D:\Entwicklung\electron-vue-app\dummy_data\IMG_6176 - Cöpy.cr2 -> D:\Entwicklung\electron-vue-app\dummy_data\IMG_6176 - Cöpy.cr2.thumbnail.jpg
Thumbnail extraction failed: Error: File not found - D:/Entwicklung/electron-vue-app/dummy_data/IMG_6176 - Cöpy.cr2
    at BinaryExtractionTask.parser (D:\Entwicklung\electron-vue-app\node_modules\exiftool-vendored\src\ExifToolTask.ts:22:19)
    at BinaryExtractionTask._Task_resolve (D:\Entwicklung\electron-vue-app\node_modules\batch-cluster\src\Task.ts:144:38)
````
Note that reading the tags works as expected!

**Comment by mceachen** [comment]
Bugfixes and tests are in new v19.0.0. Thanks for the bug report!

**Comment by jrast** [comment]
Thank you for the quick fix! I will try the new version!

**Comment by bheston** [comment]
Thanks for this! I was about to make a similar fix for another issue I don't see mentioned, which is that _every_ write action that has been done before this was fixed introduced a _mostly_ empty IPTC section. This is because `CodedCharacterSet` was specified which is an actual tag that exiftool is being told to set, not a modifier or configuration option like the others.

So now to go remove the IPTC section from all the files I've written in the past... 🤔
