### ISSUE TITLE
Tag 'XMPMeta' is not defined Build with -s ASSERTIONS=1 for more info on Mac

### ISSUE THREAD

**Issue by nagtechie** [photostructure/exiftool-vendored.js#126]
**Describe the bug**
Getting RuntimeError when writing XmpMeta Tag to the image.  This could be an OS specific specific issue where the exiftool is not build fully for XmpMeta tags to write.

```
Error: Warning: Tag 'XMPMeta' is not defined
    at WriteTask.parser (../node_modules/exiftool-vendored/dist/ExifToolTask.js:38:29)
    at WriteTask._Task_resolve (../node_modules/batch-cluster/dist/Task.js:146:40)

RuntimeError: abort(Error: Warning: Tag 'XMPMeta' is not defined). Build with -s ASSERTIONS=1 for more info.
    at process.y (../node_modules/lz4-asm/dist/lz4wasm.js:16:393)
    at process.emit (node:events:527:28)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

**To Reproduce**
code :

```  
const exif = new ExifTool()

  await exif.write("image.png", {XMPToolkit:"Exempi + XMP Core 6.0.0",
    XMPMeta:"<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\">" +
      "  <rdf:Description rdf:about=\"\"" +
      "    xmlns:ex=\"https://example.com/schemas/xsd/1.0/\">" +
      "   <ex:resolution>1025x1025</ex:resolution>" +
      "  </rdf:Description>" +
      " </rdf:RDF>"
  }) 
```

**Expected behavior**
It should not generate error. XMPMeta should be written to the file.

**Environment (please complete the following information):**
 - OS and version: Mac M1 OS X 12.6
 - Node.JS version 18.6.0

**Comment by mceachen** [comment]
It’s unclear what tags you’re trying to write to here, but you don’t feed that method an XML document. Please refer to the fine documentation: https://github.com/photostructure/exiftool-vendored.js#writing-tags
