### ISSUE TITLE
Write operation fails when metadata Struct contains Arrays

### ISSUE THREAD

**Issue by bugfest** [photostructure/exiftool-vendored.js#211]
**Describe the bug**
WriteTask fails when encoding structs containing Arrays. I tripped into this issue when trying to create RegionInfo structures (eg. https://exiftool.org/struct.html#Serialize) 

**To Reproduce**
```nodejs
# index.js
var exif = require('exiftool-vendored');

async function main() {
    const exiftool = new exif.ExifTool();
    const regionData = {
        RegionInfo: {
          AppliedToDimensions: { W: 10, H: 10, Unit: "pixel" },
          RegionList: [
            {
              Area: { X: 0.5, Y: 0.5, W: 0.1, H: 0.1, Unit: "normalized" },
              Rotation: 0,
              Type: "Face",
              Name: "name",
            }
          ],
        },
      }
      await exiftool.write('./any.jpg', regionData)
}

main();
```

```shell
npm i exiftool-vendored@28.2.1
node index.js
```

Outputs the following error:
```shell
/home/bugfest/workdir/node_modules/exiftool-vendored/dist/WriteTask.js:79
        throw new Error("cannot encode " + JSON.stringify(o));
              ^

Error: cannot encode {"AppliedToDimensions":{"W":10,"H":10,"Unit":"pixel"},"RegionList":[{"Area":{"X":0.5,"Y":0.5,"W":0.1,"H":0.1,"Unit":"normalized"},"Rotation":0,"Type":"Face","Name":"name"}]}
    at enc (/home/bugfest/workdir/node_modules/exiftool-vendored/dist/WriteTask.js:79:15)
    at WriteTask.for (/home/bugfest/workdir/node_modules/exiftool-vendored/dist/WriteTask.js:124:34)
    at /home/bugfest/workdir/node_modules/exiftool-vendored/dist/ExifTool.js:247:64
    at f (/home/bugfest/workdir/node_modules/exiftool-vendored/dist/ExifTool.js:401:50)
    at async main (/home/bugfest/workdir/index.js:18:7)

Node.js v22.9.0
```

**Expected behavior**
Script should work without errors. `RegionInfo` metadata structure should be added to the image.

**Environment (please complete the following information):**

- Version of this library: `28.2.1`
- OS and version: Debian 12 bookworm x86_64
- Node.js version: v22.9.0

**Comment by mceachen** [comment]
Nice! Thanks for taking the time to both explain the situation, reference the exiftool docs, and even provide a PR! :1st_place_medal:

**Comment by bugfest** [comment]
So kind of you! Thanks @mceachen!
