### ISSUE TITLE
Error message when file unchanged

### ISSUE THREAD

**Issue by ManuCart** [photostructure/exiftool-vendored.js#67]
With some photos files, I have an error
I try in batch and I have this response
````
exiftool -All:All= caT0jyIExEb7QsK3Gc-Aa.JPG
    0 image files updated
    1 image files unchanged
````
in nodejs
````
exiftool.write('caT0jyIExEb7QsK3Gc-Aa.JPG', {}, ["-All:All="])
````
````
Error: No success message: 0 image files updated
    1 image files unchanged
    at WriteTask.parse (/home/dev/node_modules/exiftool-vendored/dist/WriteTask.js:145:19)
    at WriteTask.parser (/home/dev/node_modules/exiftool-vendored/dist/ExifToolTask.js:55:26)
    at WriteTask.<anonymous> (/home/dev/node_modules/batch-cluster/dist/Task.js:122:51)
    at step (/home/dev/node_modules/batch-cluster/dist/Task.js:33:23)
    at Object.next (/home/dev/node_modules/batch-cluster/dist/Task.js:14:53)
    at /home/dev/node_modules/batch-cluster/dist/Task.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dev/node_modules/batch-cluster/dist/Task.js:4:12)
    at WriteTask.Task.resolve (/home/dev/node_modules/batch-cluster/dist/Task.js:116:16)
    at BatchProcess.<anonymous> (/home/dev/node_modules/batch-cluster/dist/BatchProcess.js:483:51)
    at step (/home/dev/node_modules/batch-cluster/dist/BatchProcess.js:33:23)
    at Object.next (/home/dev/node_modules/batch-cluster/dist/BatchProcess.js:14:53)
    at /home/dev/node_modules/batch-cluster/dist/BatchProcess.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/dev/node_modules/batch-cluster/dist/BatchProcess.js:4:12)
    at Timeout._onTimeout (/home/dev/node_modules/batch-cluster/dist/BatchProcess.js:476:51)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
````
How to know if file changed or not

**Comment by mceachen** [comment]
This is a common error due to you asking exiftool to make changes, and exiftool not being able to comply with your request. It's not likely to be a bug with this library. It's most likely user error that you'll need to figure out on your own.

1. Turn on debugging: https://github.com/photostructure/exiftool-vendored.js/blob/master/README.md#logging-and-events
2. Look for the exact command that is being provided to exiftool
3. Try out the exiftool command on the terminal. Enable exiftool verbose mode by adding `-v` to see what's going on.
4. Check out the extensive exiftool forum. Your specific question has most likely been asked, and answered. 

http://u88.n24.queensu.ca/exiftool/forum/

https://stackoverflow.com/questions/tagged/exiftool

I will close your "I want free help" tickets in the future. Bug reports and pull requests are always welcome.

**Comment by ManuCart** [comment]
but I told you in batch with the first command I have no error
exiftool just told me file unchanged
I have an error with your script. I have the same answer with your script but with some line errors.
It's a bug I'm pretty sure.
Please read carrefully my first post.

**Comment by mceachen** [comment]
>  exiftool just told me file unchanged

If you ask to perform an operation and the operation cannot be performed, I consider that an error.

If you'd like different error detection, feel free to add your own method. There's lots of example code in the tests.

**Comment by mceachen** [comment]
>  Please read carrefully my first post.

Please read my responses as well. Especially my very first response: In the future, don't skip over the bug report form for this project or any project. 

Do not put the burden of effort on library authors. We're doing this voluntarily. With no way to replicate your issue, no obvious "this is what happened, but this is what I expected," you're wasting everyone's time.

**Comment by mceachen** [comment]
> If you'd like different error detection, feel free to add your own method. There's lots of example code in the tests.

Specifically, you'd extend [WriteTask](https://github.com/photostructure/exiftool-vendored.js/blob/master/src/WriteTask.ts) (or just copy-and-paste the class completely) and change the `successRE` to `/[01] image files? (?:created|updated)/`
