### ISSUE TITLE
exiftool.extractThumbnail throw ' UnhandledPromiseRejectionWarning: Error: 0 output files created' error

### ISSUE THREAD

**Issue by jaaferbennasr** [photostructure/exiftool-vendored.js#76]
**Describe the bug**
hey and thank you for your work 
for some reason 
exiftool.extractThumbnail throw ' (node:19560) UnhandledPromiseRejectionWarning: Error: 0 output files created
    at BinaryExtractionTask.parse (C:\DEV-CODE\indd-exif\node_modules\exiftool-vendored\dist\BinaryExtractionTask.js:47:19)
    at BinaryExtractionTask.parser (C:\DEV-CODE\indd-exif\node_modules\exiftool-vendored\dist\ExifToolTask.js:55:26)
    at BinaryExtractionTask.<anonymous> (C:\DEV-CODE\indd-exif\node_modules\batch-cluster\dist\Task.js:122:51)
    at step (C:\DEV-CODE\indd-exif\node_modules\batch-cluster\dist\Task.js:33:23)
    at Object.next (C:\DEV-CODE\indd-exif\node_modules\batch-cluster\dist\Task.js:14:53)
    at C:\DEV-CODE\indd-exif\node_modules\batch-cluster\dist\Task.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\DEV-CODE\indd-exif\node_modules\batch-cluster\dist\Task.js:4:12)
    at BinaryExtractionTask.Task.resolve (C:\DEV-CODE\indd-exif\node_modules\batch-cluster\dist\Task.js:116:16)
    at BatchProcess.<anonymous> (C:\DEV-CODE\indd-exif\node_modules\batch-cluster\dist\BatchProcess.js:485:51)
(node:19560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Environment (please complete the following information):**
 - windows 10
 - Node.JS version v12.16.2

**Comment by jaaferbennasr** [comment]
please ignore this
