### ISSUE TITLE
Support updating tags in AVI files

### ISSUE THREAD

**Issue by medikoo** [photostructure/exiftool-vendored.js#81]
I've tried to update tags in AVI files but was presented with error:

```
Error: Writing of AVI files is not yet supported - /Users/medikoo/Projects/local-scripts/102_0914.test.AVI
    at WriteTask.parser (/usr/local/lib/node_modules/exiftool-vendored/dist/ExifToolTask.js:66:23)
    at WriteTask.<anonymous> (/usr/local/lib/node_modules/exiftool-vendored/node_modules/batch-cluster/dist/Task.js:122:51)
    at step (/usr/local/lib/node_modules/exiftool-vendored/node_modules/batch-cluster/dist/Task.js:33:23)
    at Object.next (/usr/local/lib/node_modules/exiftool-vendored/node_modules/batch-cluster/dist/Task.js:14:53)
    at /usr/local/lib/node_modules/exiftool-vendored/node_modules/batch-cluster/dist/Task.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/exiftool-vendored/node_modules/batch-cluster/dist/Task.js:4:12)
    at WriteTask.Task.resolve (/usr/local/lib/node_modules/exiftool-vendored/node_modules/batch-cluster/dist/Task.js:116:16)
    at BatchProcess.<anonymous> (/usr/local/lib/node_modules/exiftool-vendored/node_modules/batch-cluster/dist/BatchProcess.js:489:51)
    at step (/usr/local/lib/node_modules/exiftool-vendored/node_modules/batch-cluster/dist/BatchProcess.js:33:23)
```

I wonder is there a plan to provide support for that

**Comment by mceachen** [comment]
> I wonder is there a plan to provide support for that

This library reflects exactly the feature set of [ExifTool](https://exiftool.org), so when ExifTool supports it, this library will support it.

For the time being, you can write your metadata to a sidecar (which is also much safer).
